// <auto-generated />
using System;
using FinalProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Entities.MovieEntities", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("adult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("belongs_to_collection")
                        .HasColumnType("text");

                    b.Property<string>("budget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("genres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("homepage")
                        .HasColumnType("text");

                    b.Property<string>("imdb_id")
                        .HasColumnType("text");

                    b.Property<string>("original_language")
                        .HasColumnType("text");

                    b.Property<string>("original_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("overview")
                        .HasColumnType("text");

                    b.Property<string>("popularity")
                        .HasColumnType("text");

                    b.Property<string>("poster_path")
                        .HasColumnType("text");

                    b.Property<string>("production_companies")
                        .HasColumnType("text");

                    b.Property<string>("production_countries")
                        .HasColumnType("text");

                    b.Property<string>("release_date")
                        .HasColumnType("text");

                    b.Property<int?>("revenue")
                        .HasColumnType("integer");

                    b.Property<decimal?>("runtime")
                        .HasColumnType("numeric");

                    b.Property<string>("spoken_languages")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<string>("tagline")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<string>("video")
                        .HasColumnType("text");

                    b.Property<decimal?>("vote_average")
                        .HasColumnType("numeric");

                    b.Property<int?>("vote_count")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("tblMovie");
                });
#pragma warning restore 612, 618
        }
    }
}
